'use client';
import { useEffect,useState } from 'react';
import CameraCapture from '@/components/CameraCapture';
import BodyMap from '@/components/BodyMap';
import DoseResultModal from '@/components/DoseResultModal';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Result={status:'APPROVED'|'WARNING'|'BLOCKED';confidence_score:number;detected_dose:number;prescribed_dose:number;dose_match:boolean;medication_match:boolean;visual_issues:string[];action_message:string};
export default function VerifyPage(){
 const [sites,setSites]=useState<any[]>([]),[site,setSite]=useState(''),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false);const user='demo-user',prescription='demo-prescription';
 useEffect(()=>{fetch(`${API}/api/v1/body-map/next-site?user_id=${encodeURIComponent(user)}`).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(setSites).catch(()=>setSites([]))},[]);
 async function capture(file:File){if(!site){alert('Escolha primeiro um local recomendado.');return}setBusy(true);const fd=new FormData();fd.append('image',file);fd.append('prescription_id',prescription);fd.append('selected_site_id',site);fd.append('user_id',user);try{const r=await fetch(`${API}/api/v1/verify-injection`,{method:'POST',body:fd});const data=await r.json();if(!r.ok){setResult({status:'BLOCKED',confidence_score:0,detected_dose:0,prescribed_dose:0,dose_match:false,medication_match:false,visual_issues:[data.detail||'REQUEST_FAILED'],action_message:'A verificação não pôde ser concluída.'});return}setResult(data.verification)}catch{setResult({status:'BLOCKED',confidence_score:0,detected_dose:0,prescribed_dose:0,dose_match:false,medication_match:false,visual_issues:['NETWORK_ERROR'],action_message:'Não foi possível contactar o servidor de verificação.'})}finally{setBusy(false)}}
 return <main className="min-h-screen bg-slate-950 px-5 py-6 text-slate-950"><div className="mx-auto max-w-xl"><header className="mb-5 flex items-center justify-between text-white"><a href="/" className="font-bold">← PROJETO SERINGA</a><span className="text-xs text-slate-400">Área de verificação</span></header><div className="space-y-5 rounded-[2rem] bg-slate-50 p-5"><div><p className="text-sm font-semibold text-emerald-600">VERIFICAÇÃO</p><h1 className="text-3xl font-bold">Verificação inteligente</h1><p className="mt-1 text-sm text-slate-500">A IA verifica a imagem; a decisão médica continua com o profissional e a prescrição.</p></div><BodyMap sites={sites} onSelect={setSite}/><CameraCapture onCapture={capture}/>{busy&&<div className="rounded-2xl bg-blue-50 p-4 text-sm">A analisar a imagem. Se houver qualquer dúvida, o sistema bloqueia a verificação.</div>}<DoseResultModal result={result} onClose={()=>setResult(null)}/></div></div></main>;
}
