'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
function mass(v:string,u:string){const n=Number(v.replace(',','.').trim());if(!Number.isFinite(n)||n<=0)return null;return u==='g'?n*1000:u==='mcg'?n/1000:n;}
export default function VerifyPage(){
 const[dose,setDose]=useState('10'),[du,setDu]=useState('mg'),[conc,setConc]=useState('5'),[cu,setCu]=useState('mg'),[saved,setSaved]=useState(false);
 const volume=useMemo(()=>{const d=mass(dose,du),c=mass(conc,cu);return d&&c?d/c:null},[dose,du,conc,cu]);
 function save(){if(!volume)return;localStorage.setItem('seringa-last-application',new Date().toLocaleString('pt-PT'));setSaved(true)}
 return <main className="min-h-screen bg-[#F4FAFB] px-5 py-6 text-[#16343A]"><div className="mx-auto max-w-2xl"><header className="mb-8 flex items-center justify-between"><Link href="/" className="font-bold text-[#167D8D]">← PROJETO SERINGA</Link><span className="text-xs text-[#6A8388]">Conferência de dose</span></header><section className="rounded-[2rem] border border-[#D5E7E8] bg-white p-6 shadow-xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#167D8D]">Conferência Rápida de Dose</p><h1 className="mt-2 text-3xl font-black">Confira a matemática do volume.</h1><p className="mt-3 text-sm leading-6 text-[#5C777D]">Informe os dados que já constam da prescrição e do rótulo. O Seringa não prescreve, não diagnostica e não autoriza a aplicação.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><label><span className="text-sm font-bold">Dose prescrita</span><div className="mt-2 flex rounded-xl border border-[#C9DDDF]"><input aria-label="Dose prescrita" inputMode="decimal" value={dose} onChange={e=>setDose(e.target.value)} className="min-w-0 flex-1 px-4 py-3 outline-none"/><select aria-label="Unidade da dose" value={du} onChange={e=>setDu(e.target.value)} className="border-l border-[#C9DDDF] bg-white px-3"><option>mg</option><option>mcg</option><option>g</option></select></div></label><label><span className="text-sm font-bold">Concentração do rótulo</span><div className="mt-2 flex rounded-xl border border-[#C9DDDF]"><input aria-label="Concentração" inputMode="decimal" value={conc} onChange={e=>setConc(e.target.value)} className="min-w-0 flex-1 px-4 py-3 outline-none"/><select aria-label="Unidade da concentração" value={cu} onChange={e=>setCu(e.target.value)} className="border-l border-[#C9DDDF] bg-white px-3"><option>mg</option><option>mcg</option><option>g</option></select><span className="flex items-center px-3 text-sm text-[#5C777D]">/mL</span></div></label></div><div className="mt-7 rounded-2xl border border-[#B7DDD7] bg-[#F8FCFC] p-6 text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#6A8388]">Volume resultante</p><p className="mt-2 text-5xl font-black text-[#167D8D]">{volume?`${volume.toFixed(2).replace('.',',')} mL`:'—'}</p><p className="mt-3 text-sm text-[#5C777D]">Confira o rótulo do frasco e a escala da sua seringa antes de prosseguir.</p></div><button type="button" onClick={save} className="mt-6 rounded-xl bg-[#167D8D] px-5 py-3 font-bold text-white">Registrar aplicação concluída</button>{saved&&<p className="mt-3 text-sm font-semibold text-[#287E70]">Registro guardado neste aparelho.</p>}<p className="mt-6 text-xs leading-5 text-[#6A8388]">Software de apoio — não substitui avaliação ou autorização clínica.</p></section></div></main>;
}
