'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';

const features = [
  ['01', 'Conferência Visual e Matemática', 'Insira a dose prescrita e a concentração do frasco para visualizar o volume exato em mL na escala da seringa.'],
  ['02', 'Apoio e Preparação', 'Checklist simples de higiene e guia de respiração cadenciada para aplicar com mais calma e sem pressa.'],
  ['03', 'Registro Pessoal', 'Mantenha o histórico das suas aplicações guardado com segurança e confira se já tomou a dose do dia.'],
];
const faq = [
  ['O que é o Projeto Seringa?', 'É uma ferramenta de apoio reflexivo para conferir matematicamente o volume a partir dos dados da prescrição e do rótulo, além de ajudar no preparo e no registro pessoal.'],
  ['O Seringa calcula a dose que devo tomar?', 'Não. A dose vem da sua prescrição ou orientação recebida. O Seringa apenas calcula o volume correspondente aos dados que você informa e apresenta o resultado para conferência.'],
  ['O sistema bloqueia uma aplicação?', 'Não. O Seringa não autoriza nem bloqueia a sua decisão. Quando encontra dados incompletos, ambíguos ou uma possível duplicidade, apenas apresenta um alerta para você conferir a prescrição.'],
  ['O sistema usa câmera ou IA para analisar imagens?', 'Não no fluxo do aplicativo. A ferramenta principal não precisa de câmera, upload de fotos ou análise por visão computacional.'],
  ['Posso registrar se já fiz a aplicação?', 'Sim. Você pode registrar localmente uma aplicação concluída e conferir se existe um registro recente no mesmo dia. O alerta é informativo e não impede um novo registro.'],
  ['Meus dados são enviados para servidores?', 'Nesta ferramenta de conferência e registro, os dados ficam armazenados localmente no aparelho. Não é necessário criar uma conta para usar a experiência básica.'],
  ['O Seringa substitui um profissional de saúde?', 'Não. É uma ferramenta de apoio. Não prescreve, não diagnostica, não avalia aptidão clínica e não substitui orientação profissional.'],
];
function parseMass(value:string,unit:string){const n=Number(value.replace(',','.').trim());if(!Number.isFinite(n)||n<=0)return null;return unit==='g'?n*1000:unit==='mcg'?n/1000:n;}
function DoseChecker(){
 const[dose,setDose]=useState('10'),[doseUnit,setDoseUnit]=useState('mg'),[concentration,setConcentration]=useState('5'),[concentrationUnit,setConcentrationUnit]=useState('mg'),[confirmed,setConfirmed]=useState(false),[lastRecorded,setLastRecorded]=useState<string|null>(null);
 const volume=useMemo(()=>{const d=parseMass(dose,doseUnit),c=parseMass(concentration,concentrationUnit);if(d===null||c===null)return null;const r=d/c;return Number.isFinite(r)&&r>0?r:null;},[dose,doseUnit,concentration,concentrationUnit]);
 const fill=Math.min(100,Math.max(0,((volume??0)/5)*100));const stored=typeof window!=='undefined'?localStorage.getItem('seringa-last-application'):null;const today=new Date().toLocaleDateString('pt-PT');const already=Boolean(stored?.startsWith(today));
 function record(){if(!volume)return;const now=new Date(),stamp=`${now.toLocaleDateString('pt-PT')} ${now.toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}`;localStorage.setItem('seringa-last-application',stamp);setLastRecorded(stamp);setConfirmed(true);}
 return <div className="rounded-[2rem] border border-[#D5E7E8] bg-white p-5 shadow-xl"><div className="rounded-[1.5rem] bg-[#F4FAFB] p-6">
  <div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#167D8D]">Conferência Rápida de Dose</p><h2 className="mt-2 text-2xl font-black">Confira antes de preparar.</h2></div><span className="rounded-full bg-[#E5F4F1] px-3 py-1 text-xs font-semibold text-[#287E70]">Sem câmera</span></div>
  <div className="mt-7 grid gap-4 sm:grid-cols-2"><label><span className="text-sm font-bold">Dose prescrita</span><div className="mt-2 flex overflow-hidden rounded-xl border border-[#C9DDDF] bg-white"><input aria-label="Dose prescrita" inputMode="decimal" value={dose} onChange={e=>setDose(e.target.value)} className="min-w-0 flex-1 px-4 py-3 outline-none"/><select aria-label="Unidade da dose" value={doseUnit} onChange={e=>setDoseUnit(e.target.value)} className="border-l border-[#C9DDDF] bg-white px-3 outline-none"><option>mg</option><option>mcg</option><option>g</option></select></div></label>
  <label><span className="text-sm font-bold">Concentração do rótulo</span><div className="mt-2 flex overflow-hidden rounded-xl border border-[#C9DDDF] bg-white"><input aria-label="Concentração do rótulo" inputMode="decimal" value={concentration} onChange={e=>setConcentration(e.target.value)} className="min-w-0 flex-1 px-4 py-3 outline-none"/><span className="flex items-center border-l border-[#C9DDDF] px-2 text-sm text-[#5C777D]">/mL</span><select aria-label="Unidade da concentração" value={concentrationUnit} onChange={e=>setConcentrationUnit(e.target.value)} className="border-l border-[#C9DDDF] bg-white px-3 outline-none"><option>mg</option><option>mcg</option><option>g</option></select></div></label></div>
  <div className="mt-7 rounded-2xl border border-[#B7DDD7] bg-white p-5 text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#6A8388]">Volume resultante</p><p className="mt-2 text-5xl font-black text-[#167D8D]">{volume?`${volume.toFixed(2).replace('.',',')} mL`:'—'}</p><p className="mt-2 text-sm text-[#5C777D]">{volume?'A dose configurada corresponde a este volume nesta concentração.':'Confira os valores e as unidades informadas.'}</p></div>
  <div className="mt-5 rounded-2xl border border-[#D5E7E8] bg-white p-5"><div className="flex items-end justify-center gap-3"><div className="relative h-20 w-64 overflow-hidden rounded-l-xl rounded-r-full border-2 border-[#167D8D] bg-[#F4FAFB]"><div className="absolute inset-y-0 left-0 bg-[#4FB3A4]/45" style={{width:`${fill}%`}}/><div className="absolute inset-0 flex items-end justify-between px-3 pb-2 text-[10px] font-bold text-[#426168]">{[0,1,2,3,4,5].map(mark=><span key={mark} className="flex h-8 flex-col items-center justify-end">{mark}<i className="mt-1 h-3 border-l border-[#426168]"/></span>)}</div></div><div className="h-3 w-12 rounded-r-full border-y border-r border-[#167D8D] bg-white"/></div><p className="mt-3 text-center text-xs text-[#6A8388]">Esquema ilustrativo de 0 a 5 mL. Compare com a escala real da sua seringa.</p></div>
  <p className="mt-5 text-sm leading-6 text-[#426168]">Confira o rótulo do frasco e a escala da sua seringa antes de prosseguir.</p><div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" onClick={record} className="rounded-xl bg-[#167D8D] px-5 py-3 text-sm font-bold text-white hover:bg-[#126B79]">Registrar aplicação concluída</button>{confirmed&&<span className="text-sm font-semibold text-[#287E70]">Registro guardado neste aparelho{lastRecorded?` às ${lastRecorded}`:''}.</span>}{!confirmed&&already&&<span className="rounded-xl bg-[#FFF7E6] px-4 py-3 text-sm font-semibold text-[#8A6417]">Consta uma aplicação registrada hoje. Verifique sua prescrição antes de registrar outra.</span>}</div>
 </div></div>;
}
function FAQ(){return <section id="perguntas" className="border-t border-[#DCEBEC] bg-white"><div className="mx-auto max-w-4xl px-6 py-20 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#167D8D]">Perguntas frequentes</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Tudo explicado de forma simples.</h2><div className="mt-10 space-y-3">{faq.map(([q,a])=><details key={q} className="group rounded-2xl border border-[#D5E7E8] bg-[#F8FCFC] p-5"><summary className="cursor-pointer list-none pr-8 font-bold text-[#16343A]">{q}<span className="float-right text-[#167D8D]">+</span></summary><p className="mt-3 max-w-3xl leading-7 text-[#5C777D]">{a}</p></details>)}</div></div></section>}
export default function Home(){return <main className="min-h-screen bg-[#F4FAFB] text-[#16343A]"><nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5 lg:px-8"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#167D8D] font-black text-white">S</span><span><b className="block tracking-tight">PROJETO SERINGA</b><small className="text-[#5C777D]">Apoio simples para conferir e registrar</small></span></Link><div className="hidden items-center gap-8 text-sm text-[#426168] md:flex"><a href="#como-funciona">Como funciona</a><a href="#privacidade">Privacidade</a><a href="#perguntas">Perguntas</a></div><a href="#conferencia" className="rounded-full bg-[#167D8D] px-5 py-2.5 text-sm font-bold text-white">Conferir dose</a></nav>
<section className="mx-auto grid max-w-6xl gap-12 px-6 pb-24 pt-12 lg:grid-cols-[.9fr_1.1fr] lg:px-8 lg:pt-20"><div className="self-center"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#B7DDD7] bg-white px-4 py-2 text-xs font-semibold text-[#167D8D]"><span className="h-2 w-2 rounded-full bg-[#4FB3A4]"/> Feito para ser simples</div><h1 className="max-w-3xl text-5xl font-black leading-[1.05] tracking-tight sm:text-6xl">Mais clareza para conferir, preparar e <span className="text-[#167D8D]">registrar.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#426168]">O Seringa é uma ferramenta de apoio reflexivo para conferir matematicamente o volume, preparar-se com calma e registrar o que foi feito.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#conferencia" className="rounded-2xl bg-[#167D8D] px-6 py-3.5 font-bold text-white">Começar conferência</a><a href="#como-funciona" className="rounded-2xl border border-[#C9DDDF] bg-white px-6 py-3.5 font-semibold">Como funciona</a></div><p className="mt-5 max-w-xl text-xs leading-5 text-[#6A8388]">Software de apoio — não diagnostica, não prescreve, não avalia aptidão clínica e não autoriza injeções.</p></div><div id="conferencia"><DoseChecker/></div></section>
<section id="como-funciona" className="border-y border-[#DCEBEC] bg-white"><div className="mx-auto max-w-6xl px-6 py-20 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#167D8D]">Como funciona</p><h2 className="mt-3 max-w-2xl text-3xl font-bold">Três passos. Sem complicação.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{features.map(([n,t,d])=><article key={n} className="rounded-3xl border border-[#D5E7E8] bg-[#F8FCFC] p-6"><span className="text-sm font-bold text-[#167D8D]">{n}</span><h3 className="mt-8 text-xl font-bold">{t}</h3><p className="mt-3 leading-7 text-[#5C777D]">{d}</p></article>)}</div></div></section>
<section id="seguranca" className="mx-auto max-w-6xl px-6 py-20 lg:px-8"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#167D8D]">Segurança</p><h2 className="mt-3 text-3xl font-bold">Quando há inconsistência, o sistema avisa.</h2><p className="mt-5 leading-8 text-[#5C777D]">Quando há inconsistência, o sistema avisa. Se os dados informados parecerem incompletos, ambíguos ou duplicados no mesmo dia, o sistema emite um alerta claro para você conferir a prescrição antes de prosseguir. A decisão final é sempre sua e da sua equipe de saúde.</p></div><div className="rounded-3xl border border-[#D5E7E8] bg-white p-7"><ul className="space-y-5 text-sm text-[#426168]"><li><b>Conferência:</b> os dados são apresentados para você revisar.</li><li><b>Sem bloqueio:</b> alertas informam inconsistências sem impedir sua decisão.</li><li><b>Duplicidade:</b> um registro recente pode gerar um lembrete neutro.</li><li><b>Decisão:</b> o aplicativo não substitui sua prescrição nem sua equipe de saúde.</li></ul></div></div></section>
<section id="privacidade" className="bg-[#DDF3F0]"><div className="mx-auto max-w-6xl px-6 py-16 lg:px-8"><p className="text-sm font-black uppercase tracking-[.2em] text-[#167D8D]">Privacidade e Segurança</p><h2 className="mt-3 text-3xl font-black">Seus dados ficam sob seu controle.</h2><div className="mt-8 grid gap-4 md:grid-cols-3"><article className="rounded-3xl border border-[#B7DDD7] bg-white p-6"><h3 className="text-xl font-bold">100% no seu aparelho</h3><p className="mt-3 leading-7 text-[#5C777D]">Nesta ferramenta de conferência e registro, os dados de uso ficam no aparelho e não são enviados para servidores externos.</p></article><article className="rounded-3xl border border-[#B7DDD7] bg-white p-6"><h3 className="text-xl font-bold">Sem necessidade de conta</h3><p className="mt-3 leading-7 text-[#5C777D]">Use a experiência básica de imediato, sem cadastros burocráticos.</p></article><article className="rounded-3xl border border-[#B7DDD7] bg-white p-6"><h3 className="text-xl font-bold">Seus dados sob seu controle</h3><p className="mt-3 leading-7 text-[#5C777D]">O histórico é local e pode ser apagado pelo utilizador a qualquer momento.</p></article></div></div></section>
<FAQ/><footer className="mx-auto flex max-w-6xl flex-col gap-3 px-6 py-10 text-xs text-[#6A8388] sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>© 2026 Projeto Seringa</span><span>Software de apoio — não substitui avaliação ou autorização clínica.</span></footer></main>}
