'use client';
import { useEffect, useMemo, useState } from 'react';
import ProPanel from './pro';

type Tab = 'check' | 'records' | 'pro';
const features = [
  ['💉','Conferência Visual','Veja o volume com clareza antes de continuar.'],
  ['🫁','Mão Firme','Uma pausa guiada para desacelerar.'],
  ['🧭','Proteção da Pele','Organize o histórico e o rodízio.'],
  ['🔒','100% Privado','Os seus registros ficam no aparelho.'],
];
function calc(dose:string, conc:string){
  const d=Number(dose.replace(',','.')), c=Number(conc.replace(',','.'));
  if(!Number.isFinite(d)||!Number.isFinite(c)||d<=0||c<=0)return null;
  const v=d/(c*1000); return Number.isFinite(v)&&v>0?v:null;
}
function Slider(){
 const [i,setI]=useState(0); const slides=[
  ['RÉGUA VISUAL','Veja o volume com clareza','0,25 mL','💉'],
  ['RESPIRAÇÃO 4-7-8','Respire e desacelere','Uma pausa antes de continuar.','🫁'],
  ['HISTÓRICO','Veja a sua jornada','Aplicações e rodízio organizados.','🧭']
 ]; useEffect(()=>{const t=setInterval(()=>setI(x=>(x+1)%3),5000);return()=>clearInterval(t)},[]);
 return <div className="mx-auto w-full max-w-[300px] rounded-[34px] bg-[#163B36] p-2.5 shadow-[0_18px_45px_rgba(22,59,54,.18)]"><div className="rounded-[27px] bg-[#F3FAF7] p-4"><div className="flex justify-between text-[11px] font-black text-[#1B6B63]"><span>SERINGA</span><span>●</span></div><div className="relative h-[270px]">{slides.map((s,n)=><button key={s[0]} onClick={()=>setI(n)} className={`absolute inset-0 grid place-content-center gap-3 text-center transition-all ${i===n?'opacity-100':'pointer-events-none translate-x-3 opacity-0'}`}><small className="font-black tracking-[.16em] text-[#1B6B63]">{s[0]}</small><b className="text-xl leading-tight text-[#173B38]">{s[1]}</b><span className="mx-auto grid h-28 w-28 place-items-center rounded-full bg-[#D8EEDF] text-5xl">{s[3]}</span><span className="text-xs text-[#607773]">{s[2]}</span></button>)}</div><div className="flex justify-center gap-2">{slides.map((_,n)=><button aria-label={`Slide ${n+1}`} key={n} onClick={()=>setI(n)} className={`h-2.5 w-2.5 rounded-full ${i===n?'bg-[#1B6B63]':'bg-[#BCD0CB]'}`}/>)}</div></div></div>
}
function InstallButton(){
 const [deferred,setDeferred]=useState<any>(null),[installed,setInstalled]=useState(false);
 useEffect(()=>{const onBefore=(e:any)=>{e.preventDefault();setDeferred(e)};const onInstalled=()=>{setInstalled(true);setDeferred(null)};window.addEventListener('beforeinstallprompt',onBefore);window.addEventListener('appinstalled',onInstalled);return()=>{window.removeEventListener('beforeinstallprompt',onBefore);window.removeEventListener('appinstalled',onInstalled)}},[]);
 async function install(){if(deferred){deferred.prompt();await deferred.userChoice;setDeferred(null);return}alert('Android/Chrome: menu â†’ Instalar aplicativo. iPhone/iPad: Partilhar â†’ Adicionar ao ecrÃ£ principal.');}
 return <button onClick={install} className="flex w-full items-center gap-3 rounded-2xl border border-[#B9D9D2] bg-white px-4 py-3 text-left shadow-sm"><span className="text-2xl">ðŸ“²</span><span className="flex-1"><b className="block text-sm text-[#173B38]">{installed?'SERINGA instalado':'Baixar / Instalar Aplicativo'}</b><small className="text-xs text-[#607773]">Funciona sem Internet depois da instalaÃ§Ã£o</small></span><b className="text-xl text-[#1B6B63]">â€º</b></button>
}export default function Home(){
 const [tab,setTab]=useState<Tab>('check'),[dose,setDose]=useState(''),[conc,setConc]=useState(''),[medicine,setMedicine]=useState(''),[checks,setChecks]=useState([false,false,false,false]),[records,setRecords]=useState<string[]>([]);
 const volume=useMemo(()=>calc(dose,conc),[dose,conc]);
 useEffect(()=>{try{setRecords(JSON.parse(localStorage.getItem('seringa_records')||'[]'))}catch{}},[]);
 useEffect(()=>{if('serviceWorker' in navigator){navigator.serviceWorker.register('/projeto-seringa2/sw.js').catch(()=>{})}},[]);
 function save(){if(!volume)return;const item=`${new Date().toLocaleDateString('pt-PT')} · ${medicine||'Medicamento'} · ${volume.toFixed(2).replace('.',',')} mL`;const next=[item,...records];setRecords(next);localStorage.setItem('seringa_records',JSON.stringify(next));setTab('records')}
 return <main className="min-h-screen bg-[#F0F7F6] pb-24 text-[#173B38]">
  <header className="mx-auto max-w-3xl px-4 pb-3 pt-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#D8EEDF] text-2xl">💉</div><div><b className="block text-xl tracking-wide">SERINGA</b><small className="text-xs text-[#607773]">Uma conferência de cada vez, com calma.</small></div></div><span className="rounded-full bg-white px-3 py-1.5 text-[10px] font-black text-[#1B6B63] shadow-sm">🔒 PRIVADO</span></div><div className="mt-3"><InstallButton/></div></header>
  <section className="mx-auto grid max-w-5xl items-center gap-8 px-4 py-5 md:grid-cols-[1fr_300px] md:py-10"><div><span className="font-black text-xs tracking-[.18em] text-[#1B6B63]">SERINGA</span><h1 className="mt-2 text-[2.3rem] font-black leading-[1.04] tracking-tight sm:text-5xl">Mais calma.<br/>Mais clareza.<br/><span className="text-[#1B6B63]">Uma etapa de cada vez.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-[#607773]">Uma experiência simples para conferir, registrar e acompanhar — diretamente no seu celular.</p><button onClick={()=>document.getElementById('check')?.scrollIntoView({behavior:'smooth'})} className="mt-5 w-full rounded-2xl bg-[#1B6B63] px-5 py-4 font-black text-white shadow-lg md:w-auto">💉 Iniciar Minha Conferência</button></div><Slider/></section>
  <section className="mx-auto grid max-w-5xl grid-cols-2 gap-2.5 px-4 pb-5 md:grid-cols-4">{features.map(f=><article key={f[1]} className="rounded-2xl border border-[#DCE9E6] bg-white p-3 shadow-sm"><span className="text-xl">{f[0]}</span><b className="mt-1 block text-xs">{f[1]}</b><small className="text-[10px] text-[#607773]">{f[2]}</small></article>)}</section>
  {tab==='check'&&<section id="check" className="mx-auto max-w-3xl px-4"><div className="mb-3 rounded-2xl border border-[#CFE3DE] bg-white p-4"><small className="font-black tracking-[.14em] text-[#1B6B63]">ANTES DA CONFERÊNCIA</small><h2 className="mt-1 text-xl font-black">Vamos fazer a sua conferência?</h2><p className="text-xs text-[#607773]">Sem pressa. Confira cada etapa no seu ritmo.</p></div><div className="rounded-[22px] border border-[#DCE7E4] bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><small className="font-black text-[#1B6B63]">CHECKLIST</small><h3 className="font-black">Preparação</h3></div><b className="rounded-full bg-[#D8EEDF] px-3 py-1 text-xs text-[#1B6B63]">{checks.filter(Boolean).length}/4</b></div><div className="grid gap-2">{['Higienizei as mãos','Preparei o material','Conferi o medicamento','Preparei o local'].map((x,n)=><label key={x} className="flex items-center gap-3 rounded-xl border border-[#E1E7E5] p-3"><input type="checkbox" checked={checks[n]} onChange={e=>setChecks(c=>c.map((v,j)=>j===n?e.target.checked:v))} className="h-5 w-5 accent-[#1B6B63]"/><span className="text-sm font-semibold">{x}</span></label>)}</div></div>
  <div className="mt-3 rounded-[22px] border border-[#DCE7E4] bg-white p-4 shadow-sm"><small className="font-black tracking-[.14em] text-[#1B6B63]">CONFERÊNCIA DA DOSE</small><h3 className="mt-1 text-xl font-black">Informe os dados</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Dose prescrita (mcg)<input value={dose} onChange={e=>setDose(e.target.value)} inputMode="decimal" placeholder="Ex: 250" className="mt-1 h-13 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 text-base text-[#111827] outline-none focus:border-[#1B6B63]"/></label><label className="text-sm font-bold">Concentração do rótulo (mg/mL)<input value={conc} onChange={e=>setConc(e.target.value)} inputMode="decimal" placeholder="Ex: 1" className="mt-1 h-13 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 text-base text-[#111827] outline-none focus:border-[#1B6B63]"/></label><label className="text-sm font-bold sm:col-span-2">Medicamento (opcional)<input value={medicine} onChange={e=>setMedicine(e.target.value)} placeholder="Ex: Medicamento" className="mt-1 h-13 w-full rounded-xl border border-[#CBD5E1] bg-white px-3 text-base text-[#111827] outline-none focus:border-[#1B6B63]"/></label></div>{volume!==null&&<div className="mt-4 rounded-2xl bg-[#F5FAF8] p-4 text-center"><small className="text-xs text-[#607773]">VOLUME CALCULADO</small><strong className="block text-4xl text-[#1B6B63]">{volume.toFixed(2).replace('.',',')} mL</strong><p className="text-xs text-[#607773]">Confira sempre os dados com a prescrição e o rótulo.</p><div className="mt-3 h-10 overflow-hidden rounded-full border-2 border-[#1B6B63] bg-white"><div className="h-full bg-[#D8EEDF]" style={{width:`${Math.min(volume/5*100,100)}%`}}/></div></div>}<button disabled={!volume} onClick={save} className="mt-4 w-full rounded-xl bg-[#1B6B63] py-3.5 font-black text-white disabled:cursor-not-allowed disabled:opacity-40">✓ Confirmar e Salvar Aplicação</button></div></section>}
  {tab==='records'&&<section className="mx-auto max-w-3xl px-4"><div className="rounded-2xl bg-white p-5"><small className="font-black text-[#1B6B63]">SEU HISTÓRICO</small><h2 className="text-3xl font-black">Meus Registros</h2>{records.length?<div className="mt-4 grid gap-2">{records.map((r,i)=><div key={i} className="rounded-xl border border-[#DCE7E4] p-3">💉 <b>{r}</b></div>)}</div>:<div className="mt-5 rounded-2xl border border-dashed border-[#C9D9D5] p-8 text-center"><div className="text-4xl">📋</div><b>Ainda não há registros</b><p className="text-sm text-[#607773]">Quando confirmar uma aplicação, ela aparecerá aqui.</p></div>}</div></section>}
  {tab==='pro'&&<ProPanel/>}
  <nav className="fixed bottom-0 left-0 right-0 z-20 mx-auto grid h-[72px] max-w-3xl grid-cols-3 border-t border-[#D7E2DF] bg-white/95 shadow-[0_-5px_20px_rgba(35,70,65,.07)] backdrop-blur"><TabButton active={tab==='check'} onClick={()=>setTab('check')} icon="💉" text="Conferência"/><TabButton active={tab==='records'} onClick={()=>setTab('records')} icon="📋" text="Meus Registros"/><TabButton active={tab==='pro'} onClick={()=>setTab('pro')} icon="⭐" text="Seringa Pro"/></nav>
 </main>
}
function TabButton({active,onClick,icon,text}:{active:boolean,onClick:()=>void,icon:string,text:string}){return <button onClick={onClick} className={`grid place-items-center content-center gap-1 text-lg ${active?'text-[#1B6B63]':'text-[#71817E]'}`}><span>{icon}</span><small className="text-[10px] font-black">{text}</small></button>}
